/* eslint-disable prettier/prettier */
import { KatexSnippetDefinition } from '@renderer/types/katex-snippet-definition'

export const greekAllLettersSnippets: KatexSnippetDefinition[] = [
  { id: 'alpha', label: 'Alpha', latex: '\\alpha', symbol: 'α' },
  { id: 'capital-alpha', label: 'Capital Alpha', latex: '\\Alpha', symbol: 'Α' },
  { id: 'beta', label: 'Beta', latex: '\\beta', symbol: 'β' },
  { id: 'capital-beta', label: 'Capital Beta', latex: '\\Beta', symbol: 'Β' },
  { id: 'gamma', label: 'Gamma', latex: '\\gamma', symbol: 'γ' },
  { id: 'capital-gamma', label: 'Capital Gamma', latex: '\\Gamma', symbol: 'Γ' },
  { id: 'delta', label: 'Delta', latex: '\\delta', symbol: 'δ' },
  { id: 'capital-delta', label: 'Capital Delta', latex: '\\Delta', symbol: 'Δ' },
  { id: 'epsilon', label: 'Epsilon', latex: '\\epsilon', symbol: 'ε' },
  { id: 'capital-epsilon', label: 'Capital Epsilon', latex: '\\Epsilon', symbol: 'Ε' },
  { id: 'zeta', label: 'Zeta', latex: '\\zeta', symbol: 'ζ' },
  { id: 'capital-zeta', label: 'Capital Zeta', latex: '\\Zeta', symbol: 'Ζ' },
  { id: 'eta', label: 'Eta', latex: '\\eta', symbol: 'η' },
  { id: 'capital-eta', label: 'Capital Eta', latex: '\\Eta', symbol: 'Η' },
  { id: 'theta', label: 'Theta', latex: '\\theta', symbol: 'θ' },
  { id: 'capital-theta', label: 'Capital Theta', latex: '\\Theta', symbol: 'Θ' },
  { id: 'iota', label: 'Iota', latex: '\\iota', symbol: 'ι' },
  { id: 'capital-iota', label: 'Capital Iota', latex: '\\Iota', symbol: 'Ι' },
  { id: 'kappa', label: 'Kappa', latex: '\\kappa', symbol: 'κ' },
  { id: 'capital-kappa', label: 'Capital Kappa', latex: '\\Kappa', symbol: 'Κ' },
  { id: 'lambda', label: 'Lambda', latex: '\\lambda', symbol: 'λ' },
  { id: 'capital-lambda', label: 'Capital Lambda', latex: '\\Lambda', symbol: 'Λ' },
  { id: 'mu', label: 'Mu', latex: '\\mu', symbol: 'μ' },
  { id: 'capital-mu', label: 'Capital Mu', latex: '\\Mu', symbol: 'Μ' },
  { id: 'nu', label: 'Nu', latex: '\\nu', symbol: 'ν' },
  { id: 'capital-nu', label: 'Capital Nu', latex: '\\Nu', symbol: 'Ν' },
  { id: 'xi', label: 'Xi', latex: '\\xi', symbol: 'ξ' },
  { id: 'capital-xi', label: 'Capital Xi', latex: '\\Xi', symbol: 'Ξ' },
  { id: 'omicron', label: 'Omicron', latex: '\\omicron', symbol: 'ο' },
  { id: 'capital-omicron', label: 'Capital Omicron', latex: '\\Omicron', symbol: 'Ο' },
  { id: 'pi', label: 'Pi', latex: '\\pi', symbol: 'π' },
  { id: 'capital-pi', label: 'Capital Pi', latex: '\\Pi', symbol: 'Π' },
  { id: 'rho', label: 'Rho', latex: '\\rho', symbol: 'ρ' },
  { id: 'capital-rho', label: 'Capital Rho', latex: '\\Rho', symbol: 'Ρ' },
  { id: 'sigma', label: 'Sigma', latex: '\\sigma', symbol: 'σ' },
  { id: 'capital-sigma', label: 'Capital Sigma', latex: '\\Sigma', symbol: 'Σ' },
  { id: 'tau', label: 'Tau', latex: '\\tau', symbol: 'τ' },
  { id: 'capital-tau', label: 'Capital Tau', latex: '\\Tau', symbol: 'Τ' },
  { id: 'upsilon', label: 'Upsilon', latex: '\\upsilon', symbol: 'υ' },
  { id: 'capital-upsilon', label: 'Capital Upsilon', latex: '\\Upsilon', symbol: 'Υ' },
  { id: 'phi', label: 'Phi', latex: '\\phi', symbol: 'φ' },
  { id: 'capital-phi', label: 'Capital Phi', latex: '\\Phi', symbol: 'Φ' },
  { id: 'chi', label: 'Chi', latex: '\\chi', symbol: 'χ' },
  { id: 'capital-chi', label: 'Capital Chi', latex: '\\Chi', symbol: 'Χ' },
  { id: 'psi', label: 'Psi', latex: '\\psi', symbol: 'ψ' },
  { id: 'capital-psi', label: 'Capital Psi', latex: '\\Psi', symbol: 'Ψ' },
  { id: 'omega', label: 'Omega', latex: '\\omega', symbol: 'ω' },
  { id: 'capital-omega', label: 'Capital Omega', latex: '\\Omega', symbol: 'Ω' }
]
